import {
  type IconDefinition,
  faAws,
  faPhp,
  faJs,
  faNodeJs,
  faJava,
  faPython,
  faGitAlt,
  faGithub,
  faYoutubeSquare,
  faDocker,
  faGolang,
  faLaravel,
  faCloudflare,
} from '@fortawesome/free-brands-svg-icons';

export const techData: Record<string, { source: IconDefinition | string; category: string; level: string; link: string, color?: string }> = {
  'Bitbucket': {
    source: 'bitbucket.webp',
    category: 'Tool',
    level: 'Experienced',
    link: 'https://bitbucket.org/product/',
  },
  'Docker': {
    source: faDocker,
    category: 'Tool',
    level: 'Experienced',
    link: 'https://www.docker.com',
    color: 'text-blue-500',
  },
  'Git': {
    source: faGitAlt,
    category: 'Tool',
    level: 'Experienced',
    link: 'https://git-scm.com',
    color: 'text-orange-600',
  },
  'GitHub': {
    source: faGithub,
    category: 'Tool',
    level: 'Experienced',
    link: 'https://github.com',
  },
  'Gradle': {
    source: 'gradle.webp',
    category: 'Tool',
    level: 'Experienced',
    link: 'https://gradle.org/',
  },
  'JavaScript': {
    source: faJs,
    category: 'Front',
    level: 'Experienced',
    link: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript',
    color: 'text-yellow-500',
  },
  'Java': {
    source: faJava,
    category: 'Back',
    level: 'Experienced',
    link: 'https://www.java.com/en',
    color: 'text-red-600',
  },
  'JWT': {
    source: 'jwt.webp',
    category: 'Tool',
    level: 'Experienced',
    link: 'https://www.jwt.io/',
  },
  'Maven': {
    source: 'maven.svg',
    category: 'Tool',
    level: 'Experienced',
    link: 'https://maven.apache.org/',
  },
  'MySQL': {
    source: 'mysql.webp',
    category: 'Tool',
    level: 'Experienced',
    link: 'https://www.mysql.com',
  },
  'Node.js': {
    source: faNodeJs,
    category: 'Back',
    level: 'Experienced',
    link: 'https://nodejs.org/en',
    color: 'text-green-600',
  },
  'PHP': {
    source: faPhp,
    category: 'Back',
    level: 'Experienced',
    link: 'https://www.php.net/',
    color: 'text-indigo-500',
  },
  'PostgreSQL': {
    source: 'postgres.webp',
    category: 'Tool',
    level: 'Experienced',
    link: 'https://www.postgresql.org',
  },
  'Python': {
    source: faPython,
    category: 'Back',
    level: 'Experienced',
    link: 'https://www.python.org',
    color: 'text-indigo-700',
  },
  'Kafka': {
    source: 'kafka.webp',
    category: 'Tool',
    level: 'Experienced',
    color: 'invert',
    link: 'https://kafka.apache.org/'
  },
  'RabbitMQ': {
    source: 'rabbitmq.webp',
    category: 'Tool',
    level: 'Experienced',
    link: 'https://www.rabbitmq.com'
  },
  'AWS S3': {
    source: faAws,
    category: 'Tool',
    level: 'Experienced',
    link: 'https://aws.amazon.com/s3/',
  },
  'Playwright': {
    source: 'playwright.webp',
    category: 'Tool',
    level: 'Experienced',
    link: 'https://playwright.dev/',
  },
  'Postman': {
    source: 'postman.webp',
    category: 'Tool',
    level: 'Experienced',
    color: 'text-orange-500',
    link: 'https://www.postman.com/',
  },
  'Strapi': {
    source: 'strapi.svg',
    category: 'Back',
    level: 'Learning',
    link: 'https://strapi.io/',
  },
  'Supabase': {
    source: 'supabase.svg',
    category: 'Back',
    level: 'Experienced',
    link: 'https://supabase.com/',
  },
  'Svelte': {
    source: 'svelte.svg',
    category: 'Front',
    level: 'Experienced',
    link: 'https://svelte.dev',
  },
  'Tailwind': {
    source: 'tailwind.webp',
    category: 'Front',
    level: 'Experienced',
    link: 'https://tailwindcss.com/',
  },
  'TypeScript': {
    source: 'typescript.webp',
    category: 'Front',
    level: 'Experienced',
    link: 'https://www.typescriptlang.org',
  },
  'Vite': {
    source: 'vite.svg',
    category: 'Front',
    level: 'Experienced',
    link: 'https://vitejs.dev',
  },
  'Vue.js': {
    source: 'vue.webp',
    category: 'Front',
    level: 'Learning',
    link: 'https://vuejs.org/',
  },
  'Cloudflare': {
    source: faCloudflare,
    category: 'Tool',
    level: 'Learning',
    color: 'text-orange-400',
    link: 'https://www.cloudflare.com/',
  },
  'YouTube API': {
    source: faYoutubeSquare,
    category: 'Tool',
    level: 'Experienced',
    link: 'https://developers.google.com/youtube/v3/getting-started',
    color: 'text-red-600',
  },
  'Spring Boot': {
    source: 'spring-icon.svg',
    category: 'Back',
    level: 'Experienced',
    link: 'https://spring.io'
  },
  'Hibernate/JPA': {
    source: 'hibernate.webp',
    category: 'Back',
    level: 'Experienced',
    link: 'https://hibernate.org'
  },
  'Laravel': {
    source: faLaravel,
    category: 'Back',
    level: 'Experienced',
    link: 'https://laravel.com',
    color: 'text-red-700',
  },
  'Go': {
    source: faGolang,
    category: 'Back',
    level: 'Want',
    link: 'https://golang.org/',
    color: 'text-blue-400',
  },
  // 'C#': {
  //   source: 'cSharp.webp',
  //   category: 'Back',
  //   level: 'Want',
  //   link: 'https://dotnet.microsoft.com/es-es/languages/csharp'
  // },
  // '.NET': {
  //   source: 'dotNET.svg',
  //   category: 'Back',
  //   level: 'Want',
  //   link: 'https://dotnet.microsoft.com/es-es/'
  // },
};
